### ISSUE TITLE
Text below Home page intro video is sparse.

### ISSUE THREAD

**Issue by mlssamrtn** [GlobalLives/globallives#435]
If this is supposed to be a sub-header then the type styling should follow standards set for Secondary Headers. As seen in the Style Guide specs - Subheaders should be between 24 - 54pt in size.

If more copy is planned for this area, please specify what type and how much so we can establish the typesetting and layout. 
![screen shot 2014-03-16 at 8 38 41 pm](https://f.cloud.github.com/assets/6052140/2433191/b28366f0-ad85-11e3-90ff-3cfec3f9af22.png)

**Comment by bennmeyers** [comment]
issue continues, resolution needed
