### ISSUE TITLE
Multi-select interaction on Volunteer form

### ISSUE THREAD

**Issue by mlssamrtn** [GlobalLives/globallives#441]
- Please just make this a multi-select check list, not a right-click interaction.
- Remove the "Use command+click (mac) or control+click (windows) to select more than one." text
  ![screen shot 2014-03-16 at 9 08 37 pm](https://f.cloud.github.com/assets/6052140/2433309/1529a946-ad8a-11e3-8cf7-159b68a9ca28.png)

**Comment by bennmeyers** [comment]
this functions as expected
