### ISSUE TITLE
[Profile] Email User icon and link missing from profile page 

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#522]
Please compare current to wireframe:

Current:
![screen shot 2014-07-08 at 9 55 57 am](https://cloud.githubusercontent.com/assets/6045704/3514506/90e1febc-06cc-11e4-9b38-47d95a179ee7.png)

Wireframe:
![image](https://cloud.githubusercontent.com/assets/6045704/3514508/95b89bbc-06cc-11e4-9e49-606f0b1d9a31.png)

**Comment by bennmeyers** [comment]
cannot replicate
