### ISSUE TITLE
[VIDEO DETAIL] "Click to tag or comment" text to be improved 

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#546]
1) The text font and overall design looks different from the rest of the website

2) I was misled by message, it looks like the user should click the message to comment, but in reality they can click anywhere in the play bar. 

@mlssamrtn, what are your thoughts about that?

![screen shot 2014-07-08 at 9 30 03 am](https://cloud.githubusercontent.com/assets/6045704/3546234/d4c4e8a0-0880-11e4-9147-533fb81dda56.png)

**Comment by bennmeyers** [comment]
YT issue, not GLP
