### ISSUE TITLE
[VIDEO DETAIL] Comments box doesn't go away

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#548]
The comment window will only go away when the mouse is taken out of the playback bar completely. 

The window keeps being displayed  when the user drags the playback button back or forward.

There should be an x button to close the comment window.

current 
![screen shot 2014-07-10 at 3 50 31 pm](https://cloud.githubusercontent.com/assets/6045704/3546390/099ea46a-0883-11e4-9c9d-72b7620efb42.png)

wireframe

![image](https://cloud.githubusercontent.com/assets/6045704/3546458/0b7b90d0-0884-11e4-9cea-21e8b31dc598.png)

**Comment by bennmeyers** [comment]
submitted to youtube
