### ISSUE TITLE
[VIDEO DETAIL + SEARCH] Wrong timestamps when clicking on clips from search result

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#549]
The problem only happens when you click the clip from the search result page. The playback button doesn't move forward and the times stamps showing are incorrect

![screen shot 2014-07-10 at 3 40 41 pm](https://cloud.githubusercontent.com/assets/6045704/3546424/910210fe-0883-11e4-83ff-364eeaa6fe24.png)

![screen shot 2014-07-10 at 3 54 19 pm](https://cloud.githubusercontent.com/assets/6045704/3546426/98da320c-0883-11e4-87b5-49f107b670f1.png)

**Comment by deharris** [comment]
is this still happening?
-kegan
