### ISSUE TITLE
[VIDEO DETAIL] Comments are stacking forever

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#550]
It should have a max height and once reached an internal vertical scrolling would need to occur to browse all comments.

current
![screen shot 2014-07-08 at 9 38 05 am](https://cloud.githubusercontent.com/assets/6045704/3546444/d819c27a-0883-11e4-81ce-f8e034c591fb.png)

**Comment by deharris** [comment]
how do i recreate this scenario?
-kegan

**Comment by bennmeyers** [comment]
youtube issue
