### ISSUE TITLE
[MAP VIEW] Zoom bar is missing 

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#553]
wireframes:

![screen shot 2014-07-08 at 9 39 52 am](https://cloud.githubusercontent.com/assets/6045704/3546505/0740c944-0885-11e4-9934-17e1c115775a.png)

current:

![screen shot 2014-07-08 at 9 40 01 am](https://cloud.githubusercontent.com/assets/6045704/3546664/b1ea00f2-0887-11e4-9e03-19c556cb0798.png)

**Comment by bennmeyers** [comment]
cannot replicate

**Comment by bennmeyers** [comment]
feature request
