### ISSUE TITLE
[SEARCH] Limits to the number of tags showing

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#557]
@mlssamrtn, how many tags should we limit to for one clip and one participant show in the search results?

![screen shot 2014-07-08 at 9 43 42 am](https://cloud.githubusercontent.com/assets/6045704/3546733/09ad09b4-0889-11e4-93af-a28f4ecfe46b.png)

**Comment by bennmeyers** [comment]
Cannot replicate
