### ISSUE TITLE
[SEARCH + VIDEO DETAIL] Tags not highlighted in clip

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#558]
When I click on a clip from the search results after searching for a tag (bees), the moments tagged are not highlighted until a click play.

when I click in a clip from the search result:
![image](https://cloud.githubusercontent.com/assets/6045704/3546772/c2f9d3ac-0889-11e4-887f-a21f4ab9ecbd.png)

after I click the play:
![image](https://cloud.githubusercontent.com/assets/6045704/3546781/ee88b9ca-0889-11e4-8a7c-6f29f8475f4f.png)

**Comment by bennmeyers** [comment]
unclear about this being a glp issue
