### ISSUE TITLE
[VIDEO DETAIL] Tags from search is not differentiated from other tagged moments

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#559]
Current (my search result was not highlighted, I was searching for bees):
![image](https://cloud.githubusercontent.com/assets/6045704/3546799/706df2e8-088a-11e4-9b43-88a5aa3ee13d.png)

Wireframe (example of search result for breakfast):
![screen shot 2014-07-08 at 9 45 24 am](https://cloud.githubusercontent.com/assets/6045704/3546800/779ddb82-088a-11e4-96d6-445921493e4a.png)

**Comment by bennmeyers** [comment]
Not certain about this
