### ISSUE TITLE
[SEARCH] Search results don't say how many of the same tag there are

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#560]
Current (There were 2 moments tagged with bees):
![screen shot 2014-07-08 at 9 44 39 am](https://cloud.githubusercontent.com/assets/6045704/3546825/da5ebcb4-088a-11e4-8c43-7feb0c6d3eb2.png)

Wireframe:
![screen shot 2014-07-08 at 9 44 42 am](https://cloud.githubusercontent.com/assets/6045704/3546829/e6b0e24e-088a-11e4-96fb-e0d6b4d03bb9.png)

**Comment by bennmeyers** [comment]
cannot replicate
