### ISSUE TITLE
[SEARCH] Word from search not highlighted in tag

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#561]
It should be in bold and clickable. @mlssamrtn, can you confirm where the action of clicking on the tag takes the user to?

Current(results for searching for bees):
![screen shot 2014-07-08 at 9 44 24 am](https://cloud.githubusercontent.com/assets/6045704/3546847/46420508-088b-11e4-9f4d-2cbec5fe6728.png)
![screen shot 2014-07-08 at 9 44 39 am](https://cloud.githubusercontent.com/assets/6045704/3546851/516a8734-088b-11e4-87c0-e7179820ea4d.png)

Wireframes:
![screen shot 2014-07-08 at 9 44 28 am](https://cloud.githubusercontent.com/assets/6045704/3546852/5be402da-088b-11e4-8dc0-63a693961ee3.png)
![screen shot 2014-07-08 at 9 44 42 am](https://cloud.githubusercontent.com/assets/6045704/3546855/62711bd8-088b-11e4-8f19-1cd0bcf03e1e.png)

**Comment by bennmeyers** [comment]
cannot replicate
