### ISSUE TITLE
[SEARCH] Play arrow from clip is not clickable

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#562]
Play arrows from clips on search result are not clickable, but are around it is

![screen shot 2014-07-08 at 9 44 39 am](https://cloud.githubusercontent.com/assets/6045704/3546889/f70c00f0-088b-11e4-9c8c-73c8a7eebbbc.png)

![screen shot 2014-07-08 at 9 45 05 am](https://cloud.githubusercontent.com/assets/6045704/3546890/fe8c8d18-088b-11e4-87fd-84ccda236f7e.png)

**Comment by bennmeyers** [comment]
cannot replicate
