### ISSUE TITLE
[EVENTS] Overall problems with left bar on Events page 

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#569]
Past events not showing
Upcoming events not clickable
Overall is different from wireframe

![image](https://cloud.githubusercontent.com/assets/6045704/3547041/87986d18-088f-11e4-943d-75bd873e0ab1.png)

![image](https://cloud.githubusercontent.com/assets/6045704/3547052/ed41ca7e-088f-11e4-8887-f23cc7b27d61.png)

**Comment by bennmeyers** [comment]
closing RE phomnack's comment
