### ISSUE TITLE
[BLOG] Background pictures from December 31 and before disappeared

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#570]
![image](https://cloud.githubusercontent.com/assets/6045704/3547131/c039a702-0891-11e4-8b28-bfeacaad9c73.png)

**Comment by bennmeyers** [comment]
This could be done by a student.

Option 1: identify an image in the post, find in the media area of the wordpress dashboard and set it as the featured image of the post (on the right). 

Option 2 is to let David know with a list of the Blog post URL's lacking images or why an image is needed
