### ISSUE TITLE
[EVENTS] Links are highlighted in event preview but not in the event details

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#574]
preview:

![image](https://cloud.githubusercontent.com/assets/6045704/3547213/98f6e08c-0892-11e4-8cf8-637b3eafaf7c.png)

details:

![image](https://cloud.githubusercontent.com/assets/6045704/3547216/a6b077ba-0892-11e4-93cc-6658d54ebb92.png)

**Comment by bennmeyers** [comment]
fixed on staging
