### ISSUE TITLE
[VIDEO DETAIL] Crew member details missing

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#576]
We have the photo (yey!) but not the details next to it:

Current:
![image](https://cloud.githubusercontent.com/assets/6045704/3547277/b3cd9706-0893-11e4-8446-5b769320d0ca.png)

Wireframe:
![image](https://cloud.githubusercontent.com/assets/6045704/3547280/c8cf50f4-0893-11e4-9e51-f5c20ccc2961.png)

**Comment by bennmeyers** [comment]
previous comment still current

**Comment by bennmeyers** [comment]
if "View Flickr Album." doesn't show up the correct formatting of the crew member shows up
