### ISSUE TITLE
[MOBILE] Overall issues with basic design

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#579]
![photo 1](https://cloud.githubusercontent.com/assets/6045704/3547326/d3d04426-0894-11e4-9f8d-969a43636834.PNG)
![photo 2](https://cloud.githubusercontent.com/assets/6045704/3547327/d536594a-0894-11e4-9a48-5bd365169dc9.PNG)
![photo 3](https://cloud.githubusercontent.com/assets/6045704/3547328/d661ca0c-0894-11e4-9ffa-949b64605520.PNG)
![photo 5](https://cloud.githubusercontent.com/assets/6045704/3547330/d7963ffc-0894-11e4-8148-aa0822ad32f1.PNG)
![photo 4](https://cloud.githubusercontent.com/assets/6045704/3547332/d8ea0410-0894-11e4-9b0b-8d613c5391be.PNG)

![photo 1 1](https://cloud.githubusercontent.com/assets/6045704/3547338/f4ab3c46-0894-11e4-9938-0c8d97011787.PNG)
![photo 4 1](https://cloud.githubusercontent.com/assets/6045704/3547339/f5c8d7b4-0894-11e4-8664-aaa599602517.PNG)
![photo 2 1](https://cloud.githubusercontent.com/assets/6045704/3547341/f7110cfe-0894-11e4-940b-55158b604e51.PNG)
![photo 5 1](https://cloud.githubusercontent.com/assets/6045704/3547342/f8cb3150-0894-11e4-8c7f-bbf29f9541b2.PNG)
![photo 3 1](https://cloud.githubusercontent.com/assets/6045704/3547343/f9dea77a-0894-11e4-9148-457961b3846d.PNG)

**Comment by bennmeyers** [comment]
creating more focused bugs
