### ISSUE TITLE
[LOG IN] LIVE site & Staging: Correct password is not recognized and is blocked after first attempt of log in

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#581]
User is being blocked and have to wait 20 min to try to login again even when the password is correct. After 20 min of wait, password is blocking again. 

Problems:

1) Password is not recognized even when is the correct.

2) We don't need to block the user's password.  I believe we should eliminate this password blocking system. Do you agree, @mlssamrtn and @rosawu?

**Comment by bennmeyers** [comment]
cannot replicate
