### ISSUE TITLE
[LOG IN] No link to "Retrieve lost Password" on main Log In Flow

### ISSUE THREAD

**Issue by dalilaglp** [GlobalLives/globallives#582]
There is no way to retrieve the password from the main log in flow, users need to go to http://globallives.org/wp-login.php to find the "retrieve your passoword" link. 

![image](https://cloud.githubusercontent.com/assets/6045704/3648722/0ffdd84e-110c-11e4-879a-36c508bf11d5.png)

**Comment by bennmeyers** [comment]
still an issue

**Comment by bennmeyers** [comment]
requested update from developers of Social Login
