### ISSUE TITLE
Grid view: white lines between images

### ISSUE THREAD

**Issue by deharris** [GlobalLives/globallives#613]
Chrome/mac

![cursor_and_explore_the_collection_-_global_lives_projectglobal_lives_project](https://user-images.githubusercontent.com/2689217/32202374-7ce56ac0-bd99-11e7-9394-4ffdcdf9a4c4.jpg)

**Comment by bennmeyers** [comment]
the images themselves have the lines: will correct

**Comment by bennmeyers** [comment]
Fixed: compressed all images manually
