### ISSUE TITLE
Photos on Grid view have differing corner styles, Chrome

### ISSUE THREAD

**Issue by jessica7shi** [GlobalLives/globallives#616]
<img width="1253" alt="grid photo rounded vs not rounded" src="https://user-images.githubusercontent.com/22509814/32392105-78e83b50-c091-11e7-9f26-0f9e45e6d169.png">

**Comment by bennmeyers** [comment]
I'm sorry, I can't replicate this on staging or live 
![image](https://user-images.githubusercontent.com/2591291/32393308-37f78f38-c096-11e7-8827-a083b596e06a.png)

**Comment by jessica7shi** [comment]
I zoomed in (sorry for not putting that in the notes) because I could see tiny dots where the photos were dark in the corners. I think after you zoom in the difference becomes more apparent!

**Comment by bennmeyers** [comment]
I’ll check it out

</mobile_bows>

Rev Shishin Junsei nee Benn Meyers

**Comment by bennmeyers** [comment]
no programmatic issues: Images?

**Comment by bennmeyers** [comment]
after some digging I found an image related style bug and fixed it... this will likely pop up elsewhere so I'm going to spend more time on it

**Comment by bennmeyers** [comment]
made a more global fix
