### ISSUE TITLE
Error in Spelling of Baoji in Ruixian's Box, Chrome

### ISSUE THREAD

**Issue by jessica7shi** [GlobalLives/globallives#617]
<img width="1068" alt="screen_shot_2017-11-04_at_3_52_31_pm" src="https://user-images.githubusercontent.com/22509814/32410209-74276c7a-c178-11e7-8a16-d632d5553185.png">

**Comment by bennmeyers** [comment]
Fixed in website and in spreadsheet

**Comment by jessica7shi** [comment]
<img width="1280" alt="screen shot 2018-01-10 at 8 50 48 pm" src="https://user-images.githubusercontent.com/22509814/34809149-fdb049a4-f647-11e7-9ea6-f025f9ffaaaf.png">
Still not fixed? It may have reverted after you tried to get some of Devina's work back?

**Comment by bennmeyers** [comment]
Now Baoji on staging and production: http://globallives.org/?post_type=participant&p=6604&preview=true
