### ISSUE TITLE
Timing of video on Ruixian page after clicking from explore the collection is 3:0 instead of 0:03, Chrome (there are similar errors on other people's pages as well)

### ISSUE THREAD

**Issue by jessica7shi** [GlobalLives/globallives#618]
<img width="1280" alt="screen_shot_2017-11-04_at_4_29_01_pm" src="https://user-images.githubusercontent.com/22509814/32410959-96dd370a-c18b-11e7-80c3-174ff7ff2766.png">

**Comment by bennmeyers** [comment]
fixed (I think)
