### ISSUE TITLE
Cut off of gradient in video play bar, Chrome 

### ISSUE THREAD

**Issue by jessica7shi** [GlobalLives/globallives#620]
<img width="1280" alt="screen_shot_2017-11-04_at_4_30_13_pm" src="https://user-images.githubusercontent.com/22509814/32411008-40bf55fe-c18d-11e7-8a16-00d240b12703.png">
Professor Harris already made an issue similar to this one, but I couldn't find it in the issues list so I decided to make a new one. 
This issue can be seen in how all the videos are displayed, so it's not specific to Ruixian, but I also saw it in Ruixian's videos.

**Comment by bennmeyers** [comment]
submitted to youtube
