### ISSUE TITLE
Full-screen video playing doesn't have scroll bar functionality, Chrome

### ISSUE THREAD

**Issue by jessica7shi** [GlobalLives/globallives#623]
<img width="1280" alt="screen_shot_2017-11-04_at_4_58_26_pm" src="https://user-images.githubusercontent.com/22509814/32411249-3ed71708-c193-11e7-8e3e-8bab0de54c99.png">

**Comment by bennmeyers** [comment]
This is a feature of youtube, not GLP: not a bug at all :)
