### ISSUE TITLE
awkward navigation bar layout

### ISSUE THREAD

**Issue by devinasen** [GlobalLives/globallives#627]
grey grid/map view bar is very wide. Are there supposed to be buttons linking to overall grid view/map view or should the themes menu be centered in grey space? 
![glp themes music page](https://user-images.githubusercontent.com/32832436/32419333-169224dc-c22d-11e7-8341-e2efeb2f2ead.jpg)

**Comment by devinasen** [comment]
present on all special themes pages

**Comment by bennmeyers** [comment]
agreed: fixing to not be as tall

**Comment by bennmeyers** [comment]
The themes bar is corrected
