### ISSUE TITLE
most youtube videos for abhay singh + ivan montano do not play 

### ISSUE THREAD

**Issue by devinasen** [GlobalLives/globallives#630]
abhay's player doesn't open automatically, videos unavailable
![abhay](https://user-images.githubusercontent.com/32832436/32757684-9277333a-c895-11e7-9ca9-71990cdd561c.png)

**Comment by devinasen** [comment]
huyen, seunghwan also experience similar problems

**Comment by bennmeyers** [comment]
duplicate of #614
