### ISSUE TITLE
Chrome, Logo Words Blurriness -- is there a higher res photo that we can use?

### ISSUE THREAD

**Issue by jessica7shi** [GlobalLives/globallives#636]
![screen shot 2018-04-09 at 5 07 41 pm](https://user-images.githubusercontent.com/22509814/38529354-3c1a8eb8-3c19-11e8-9f0f-0ca8484da117.png)

**Comment by bennmeyers** [comment]
cannot replicate: there is a logo we can use instead in the "Ongoing Resources," directory on the GLP shared drive
