### ISSUE TITLE
"Explore the Collection" - inconsistent capitalisation of themes

### ISSUE THREAD

**Issue by samhitasen** [GlobalLives/globallives#642]
“Explore the Collection” headings at the bottom of the spread - "childhood" and "orphanage" are lowercase whereas the other categories have the first letter capitalized. Also, why are the themes not on the top panel with the other filter categories? Once you click on one of the themes, all the other filtering options disappear whereas if you filter by any of the categories along the top (e.g. to find all the female OSPs), the other options are still available. Navigating through the themes thus seems a little more difficult than the other filtering options.
![GLP_a](https://user-images.githubusercontent.com/56944399/67893631-26c6ef00-fb14-11e9-9738-5610c7ac9bfe.png)

**Comment by bennmeyers** [comment]
live on staging

**Comment by bennmeyers** [comment]
in the WP Dashboard Participants > Themes, I also inserted a CSS fragment
