### ISSUE TITLE
World map cuts off at asia

### ISSUE THREAD

**Issue by samhitasen** [GlobalLives/globallives#643]
When viewing the OSPs via the "map view" rather than grid view under "explore the collection", the map cuts off in Asia, leaving Australia and the Pacific Ocean pretty much completely off the map. Even if we don't have OSPs from those areas, its the Global Lives Project - should the whole world map be present?
![GLP_b](https://user-images.githubusercontent.com/56944399/67894172-3f83d480-fb15-11e9-8174-a333e2241e94.png)

**Comment by bennmeyers** [comment]
this is a screen size issue

**Comment by bennmeyers** [comment]
if the window height is reduced an page reloaded the map shrinks
