### ISSUE TITLE
Blog page stats - especially Twitter

### ISSUE THREAD

**Issue by samhitasen** [GlobalLives/globallives#644]
The stats for the blog page posts all say "0", and Twitter shows "??". First, Twitter's statistics should probably be fixed, but second, why have the engagement showing at all if it's at 0? Maybe we should build more engagement first, or at least make sure the engagement statistics are accurate before presenting this information on the page. 
![GLP_c](https://user-images.githubusercontent.com/56944399/67894358-95f11300-fb15-11e9-96be-3484b421d148.png)

**Comment by bennmeyers** [comment]
I've removed this undocumented and broken functionality and it is live on staging

**Comment by bennmeyers** [comment]
live on production
